#include "../include/constants.h"

    RA RAARR[] = {
      RA_ITEM,      
      RA_ITEM_NEXT,
      RA_ITEM_PREV,
      RA_ITEM_RND,     
      RA_PLAY_START,
      RA_PLAY_STOP,
      RA_PLAY_PAUSE,    
      RA_PLAY_TOGGLE,     
      RA_PLAY_DELAY,
      RA_PLAY_DELAYMIN,
      RA_PLAY_DELAYMINON, 
      RA_PLAY_DELAYMINOFF,
      RA_PLAY_RND,       
      RA_PLAY_PL,       
      RA_PLAY_LB,       
      RA_PLAY_LT,
      RA_LSET_PL,
      RA_LSET_PLNEXT,
      RA_LSET_PLPREV,       
      RA_LSET_PLRND,       
      RA_LSET_LB,     
      RA_LSET_LBNEXT,     
      RA_LSET_LBPREV,     
      RA_LSET_LBRND,
      RA_LGET_PL,
      RA_PLI_NEW,
      RA_PLI_REM,
      RA_PLI_REP,
      RA_PL_TOFS
    };